engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths: []
plugins:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 42
    checks:
      Similar code:
        enabled: false
