language: php
dist: bionic

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer install --prefer-source
  - mkdir -p ./build/coverage

script:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
       ./vendor/bin/phpunit -v --configuration ./tests/travis/$DB.travis.xml --coverage-php ./build/coverage/coverage-$DB-$TRAVIS_PHP_VERSION-$ORM.cov
    else
       ./vendor/bin/phpunit -v --configuration ./tests/travis/$DB.travis.xml
    fi

after_script:
  - ./vendor/bin/phpcov merge --clover ./build/logs/clover.xml ./build/coverage
  - ./vendor/bin/coveralls -v --exclude-no-stmt
  #Push code climate coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  # Code should respect rules
  - composer check-quality-code

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_WEBHOOK

jobs:
  include:
    - stage: Test MySQL
      php: 7.2
      env: DB=mysql.docker MYSQL_VERSION=8.0
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    - stage: Test MySQL
      php: 7.2
      env: DB=mysqli.docker MYSQL_VERSION=8.0
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    - stage: Test PostgreSQL
      php: 7.2
      env: DB=pgsql POSTGRESQL_VERSION=11.0
      sudo: required
      before_script:
        - bash ./tests/travis/install-postgres-11.sh
    - stage: Test MySQL
      php: 7.3
      env: DB=mysql.docker MYSQL_VERSION=8.0
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    - stage: Test MySQL
      php: 7.3
      env: DB=mysqli.docker MYSQL_VERSION=8.0
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    - stage: Test PostgreSQL
      php: 7.3
      env: DB=pgsql POSTGRESQL_VERSION=11.0
      sudo: required
      before_script:
        - bash ./tests/travis/install-postgres-11.sh
    - stage: Test MySQL
      php: 7.4
      env: DB=mysql COVERAGE=yes
      services:
        - mysql
    - stage: Test MySQL
      php: 7.4
      env: DB=mysql.docker MYSQL_VERSION=5.7 COVERAGE=yes
      sudo: required
      before_script:
        - bash ./tests/travis/install-mysql-5.7.sh
    - stage: Test MySQL
      php: 7.4
      env: DB=mysql.docker MYSQL_VERSION=8.0 COVERAGE=yes
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    - stage: Test MySQL
      php: 7.4
      env: DB=mysqli COVERAGE=yes
      services:
        - mysql
    - stage: Test MySQL
      php: 7.4
      env: DB=mysqli.docker MYSQL_VERSION=5.7 COVERAGE=yes
      sudo: required
      before_script:
        - bash ./tests/travis/install-mysql-5.7.sh
    - stage: Test MySQL
      php: 7.4
      env: DB=mysqli.docker MYSQL_VERSION=8.0 COVERAGE=yes
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    - stage: Test PostgreSQL
      php: 7.4
      env: DB=pgsql POSTGRESQL_VERSION=9.6 COVERAGE=yes
      addons:
        postgresql: "9.6"
        apt:
          packages:
            - postgis
            - postgresql-9.6-postgis-2.5
    - stage: Test PostgreSQL
      php: 7.4
      env: DB=pgsql POSTGRESQL_VERSION=10.0 COVERAGE=yes
      sudo: required
      addons:
        postgresql: "10"
      before_script:
        - bash ./tests/travis/install-postgres-10.sh
    - stage: Test PostgreSQL
      php: 7.4
      env: DB=pgsql POSTGRESQL_VERSION=11.0 COVERAGE=yes
      sudo: required
      before_script:
        - bash ./tests/travis/install-postgres-11.sh
